// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TShirtShop.Data;

namespace TShirtShop.Data.Migrations
{
    [DbContext(typeof(TShirtDbContext))]
    [Migration("20210801143535_addedSeed")]
    partial class addedSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TShirtShop.Core.Models.Shirt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageLocation")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ImageThumnNailLocation")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SizeId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C# Developer",
                            Gender = 1,
                            ImageLocation = "threadbird-logo-black.jpg",
                            ImageThumnNailLocation = "threadbird-logo-black.jpg",
                            Name = "C# Developer",
                            Price = 500m,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "HTML",
                            Gender = 1,
                            ImageLocation = "world-shirt_large.jpg",
                            ImageThumnNailLocation = "world-shirt_large.jpg",
                            Name = "HTML",
                            Price = 500m,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Java Developer",
                            Gender = 1,
                            ImageLocation = "White_Tshirt.jpg",
                            ImageThumnNailLocation = "White_Tshirt.jpg",
                            Name = "Java Developer",
                            Price = 500m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "HTML",
                            Gender = 1,
                            ImageLocation = "world-shirt_large.jpg",
                            ImageThumnNailLocation = "world-shirt_large.jpg",
                            Name = "HTML",
                            Price = 500m,
                            SizeId = 3
                        });
                });

            modelBuilder.Entity("TShirtShop.Core.Models.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SizeId");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            Name = "Small"
                        },
                        new
                        {
                            SizeId = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            SizeId = 3,
                            Name = "Large"
                        });
                });

            modelBuilder.Entity("TShirtShop.Core.Models.Shirt", b =>
                {
                    b.HasOne("TShirtShop.Core.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
